#------------------------------------------------------------------
### Configurations for testing
#------------------------------------------------------------------
@token = <add access token>
@resource_group = <your resource group name>
@account_name = <Azure AI Foundry resource name>
@project_name = <Foundry project name>

@subscription_id = <subscription name>

#Common variables - Dont change these variables for now
@location_name = eastus2euap
@api_version= 2025-10-01-preview

# Variables for the resources you will create, you can name theseanything
@application_name = myapplication
@deployment_name = mydeployment

#------------------------------------------------------------------
### Create Agent Application
#------------------------------------------------------------------
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications/{{application_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties":{
    "displayName": "niceapp",
    "baseUrl": "www.doubleohseven.com",
    "agents": [{"agentName": "Publishing Agent"}]
  }
}

#------------------------------------------------------------------
### Update Agent Application
#------------------------------------------------------------------
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications/{{application_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties": {
    "displayName": "Agenty McAgentface",
    "baseUrl": "www.agenty-mcagentface.com",
    "agents": [
      {
        "agentName": "Publishing Agent"
      }
    ]
  }
}

#------------------------------------------------------------------
### List Agent Applications
#------------------------------------------------------------------
GET https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json


#------------------------------------------------------------------
### Get Agent Applications
#------------------------------------------------------------------
GET https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications/{{application_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json


#------------------------------------------------------------------
### Create Deployment for a prompt agent or workflow
#------------------------------------------------------------------
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications/{{application_name}}/agentdeployments/{{deployment_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties":{
    "description": "This is a managed deployment",
     "displayName": "Test Managed Deployment",
    "deploymentType": "Managed",
    "protocols": [
        {
          "protocol": "responses",
          "version": "1.0"
        }
    ],
    "agents": [
        {
            "agentName": "Publishing Agent",
            "agentVersion": "1"
        }
    ]

  }

}

#------------------------------------------------------------------
### Create App Deployment for a hosted agent
#------------------------------------------------------------------
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications/{{application_name}}/agentdeployments/{{deployment_name2}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties": {
    "displayName": "Test Hosted Deployment",
        "deploymentType": "Hosted",
        "minReplicas": 1,
        "maxReplicas": 1,
        "protocols": [
            {
                "protocol": "responses",
                "version": "1.0"
            }
        ],
        "agents": [
            {
                "agentName": "ContainerAgent",
                //"version": "2"
            }
        ]
  }
}

#------------------------------------------------------------------
### Create Project Deployment for a hosted agent
#------------------------------------------------------------------
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/agentdeployments/{{deployment_name2}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties": {
    "displayName": "Test Hosted Deployment",
        "deploymentType": "Hosted",
        "minReplicas": 1,
        "maxReplicas": 1,
        "protocols": [
            {
                "protocol": "responses",
                "version": "1.0"
            }
        ],
        "agents": [
            {
                "agentName": "ContainerAgent",
                "version": "1"
            }
        ]
  }
}

#------------------------------------------------------------------
### List Deployments
#------------------------------------------------------------------
GET https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications/{{application_name}}/agentdeployments?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Get Deployment
#------------------------------------------------------------------
GET https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/applications/{{application_name}}/agentdeployments/{{deployment_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json
